### ISSUE TITLE
Cannot run sample after fresh clone

### ISSUE THREAD

**Issue by alesmit** [ukaoskid/peque-fwork#3]
## Problem

Command `npm run start:sample` breaks after doing a fresh clone due to a missing directory. After manually creating an empty folder in `src/swagger/generated` I could run the sample without issues.

## Steps to reproduce

1. Clone the repository and install dependencies
3. `npm run build`
4. `npm run start:sample`

Outputs:
```bash
[1639059945921] [debug] [get] /random/echo/:echo
[1639059945922] [debug] [get] /random/number
[1639059945922] [debug] [get] /test/hello-world
[1639059945922] [debug] [get] /test/external
(node:95872) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: ENOENT: no such file or directory, stat '[...]/peque-fwork/src/swagger/generated'
    at Object.statSync (node:fs:1536:3)
    at __node_internal_ (node:internal/fs/utils:793:8)
    at Object.rmdirSync (node:fs:1156:15)
    at Object.removeFolder ([...]/peque-fwork/src/utils/fs.utils.ts:32:6)
    at SwaggerFactory.generate ([...]/peque-fwork/src/factory/swagger-factory.ts:258:5)
    at Server.<anonymous> ([...]/peque-fwork/src/server.ts:104:22)
    at Generator.next (<anonymous>)
    at [...]/peque-fwork/src/server.ts:17:71
    at new Promise (<anonymous>)
    at __awaiter ([...]/peque-fwork/src/server.ts:13:12)
```

## Expected behavior

`npm run start:sample` should create the empty directory if it doesn't exist.

**Comment by ukaoskid** [comment]
This should be solved in the last version
